# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4271e9c6a1d3855837f5e309796bcaed7c473a43712510e2d84ef389ef5112d2a9bf5b8c2d7af46989ab40917ed830cf5b8851fde893eb594aeb6595d0de651c

test:
  secret_key_base: d8fa440fb944aee6979ec4e27c0b927f2d936a9eb685be85c377c5334a5fd3a0bc8d89aea1716a7f4158a65b4fc64b685939b42745e959beed0e21938ebde2e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
